{{- if .Values.ezua.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "rundmc-whisper-nim-diarization-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rundmc-whisper-nim-diarization-app.labels" . | nindent 4 }}
    hpe-ezua/type: vendor-service
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | quote }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "rundmc-whisper-nim-diarization-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
      timeout: 300s
{{- end }}